version: "3.7"

services:
    db:
        image: mysql:5.7
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
        ports:
            - 43306:3306
            - 43060:33060

    php:
        build:
            context: .docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - .:/var/www/symfony
        depends_on:
          - db
        ports:
          - 9000:9000

    nginx:
        build: .docker/nginx
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - .:/var/www/symfony
        depends_on:
            - db
            - php
